database: mysqldb

spring:
  # MySQL
  datasource:
    driver-class-name: ${db_mysql_driver}
    url: jdbc:mysql://# ${db_mysql_url}:3306/kotlin?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${db_mysql_username}
    password: ${db_mysql_password}
  jpa:
    show-sql: true
    hibernate.ddl-auto: none # ${jpa.ddl.option}
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath*:db/${database}/schema.sql
      data-locations: classpath*:db/${database}/data.sql

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org.hibernate.type.descriptor.sql: debug # trace, info