database: mysqldb

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # ${db.mysql.driver}
    url: jdbc:mysql://localhost:3306/kotlin?characterEncoding=UTF-8&serverTimezone=UTC # ${db.mysql.url}
    username: root # ${db.mysql.username}
    password: 1234 # ${db.mysql.password}
  jpa:
    show-sql: true
    hibernate.ddl-auto: none # ${jpa.ddl.option}
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath*:db/${database}/schema.sql
      data-locations: classpath*:db/${database}/data.sql

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org.hibernate.type.descriptor.sql: trace # info