server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # MySQL
  datasource:
    driver-class-name: ${db_mysql_driver}
    url: jdbc:mysql://${db_mysql_url}:${db_mysql_port}/${db_mysql_database}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${db_mysql_username}
    password: ${db_mysql_password}

  jpa:
    show-sql: true
    hibernate.ddl-auto: ${db_mysql_ddl}
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: ${db_mysql_init}
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

cloud:
  aws:
    credentials:
      accessKey: ${aws_s3_accesskey}
      secretKey: ${aws_s3_secretkey}
    s3:
      bucket: ${aws_s3_bucket}
    region:
      static: ${aws_s3_region}
    stack:
      auto: false

logging:
  level:
    org.hibernate.type.descriptor.sql: debug # trace, info

